# ------------------------------------------------------------------------------------
# Pi-Hole is an ad-blocking DNS sinkhole that runs to block ads for connected devices.
# I run it in bridge mode, but it can also be run on host network and via macvlan.
# Bridge is the best of both worlds for me because it can be set up with reverse proxy
# and easily run on the entire network seamlessly. It should be noted that bridge mode
# means that it *necessarily* blocks across the entire network, so if there are
# incorrect blockers then Pi-Hole will have to be temporarily disabled or whitelisted.
# ------------------------------------------------------------------------------------

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: NAS
    cap_add:
      - CAP_NET_RAW
      - CAP_NET_BIND_SERVICE
      - CAP_CHOWN
    environment:
      - PIHOLE_UID=${UID}
      - PIHOLE_GID=${GID}
      - WEB_UID=${UID}
      - WEB_GID=${GID}
      - TZ=America/New_York
      - WEBPASSWORD=${PIHOLE_WEB_PASSWORD}
      - DNSMASQ_LISTENING=local
      - WEB_PORT=8000
      - DNSMASQ_USER=pihole
      - FTLCONF_LOCAL_IPV4=192.168.1.100
      - FTLCONF_CHECK_LOAD=false
    volumes:
      - /volume1/docker/pihole/dnsmasq.d:/etc/dnsmasq.d
      - /volume1/docker/pihole/pihole:/etc/pihole
    ports:
      - 8001:8000
      - 53:53/udp
    network_mode: synobridge
    restart: unless-stopped
