# ----------------------------------------------------------
# Portainer is a web GUI for container management.
# This compose file is used in Synology's Container Manager,
# since Portainer can't be used to edit itself.
# ----------------------------------------------------------

services:
  # use docker-socket-proxy for portainer's Docker access
  socket-proxy:
    container_name: portainer-socket-proxy
    image: tecnativa/docker-socket-proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks: # uses the socket proxy network
      socket_proxy:
        ipv4_address: 172.21.0.254 # manually specify IP address in subnet
    privileged: true
    ports:
      - "127.0.0.1:2375:2375" # NEVER expose this to the internet with port forwarding!
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOG_LEVEL=info
      ## Variables match the URL prefix (i.e. AUTH blocks access to /auth/* parts of the API, etc.).
      ## Granted by Default
      - EVENTS=1
      - PING=1
      - VERSION=1
      ## Revoked by Default
      # Security critical
      - AUTH=0
      - SECRETS=0
      - POST=0
      # Not always needed
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      - NODES=0
      - PLUGINS=0
      - SERVICES=1
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=1
      - VOLUMES=1

    portainer:
      image: portainer/portainer-ce
      container_name: portainer
      ports:
        - 8000:8000
        - 9000:9000
        - /volume1/docker/portainer:/data
      networks:
        - socket_proxy
        - synobridge
      command: -H tcp://socket-proxy:2375
      restart: unless-stopped

networks:
  socket_proxy:
    external: true
  synobridge:
    external: true