# -----------------------------------------------------------------
# This should not be employed as a single container, but rather as
# containers inside of existent stacks. It just exists here to 
# serve as an example container and how it can be added to a stack.
# -----------------------------------------------------------------

services:
  socket-proxy:
    container_name: <container_name>-socket-proxy
    image: tecnativa/docker-socket-proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:  # uses the socket proxy network
      socket_proxy:
        ipv4_address: 192.168.91.254 # CHANGE ME: manually specify IP address in subnet
    privileged: true
    ports:
      - "127.0.0.1:2375:2375" # NEVER expose this to the internet with port forwarding!
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOG_LEVEL=info
      ## These should all be specified according to the needs. Some values are displayed below for examples.
      ## Variables match the URL prefix (i.e. AUTH blocks access to /auth/* parts of the API, etc.).
      ## Granted by Default
      - EVENTS=1
      - PING=1
      - VERSION=1
      ## Revoked by Default
      # Security critical
      - AUTH=0
      - SECRETS=0
      - POST=1 # Watchtower
      # Not always needed
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1 # Traefik, Portainer, etc.
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=1 # Portainer
      - INFO=1 # Portainer
      - NETWORKS=1 # Portainer
      - NODES=0
      - PLUGINS=0
      - SERVICES=1 # Portainer
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=1 # Portainer
      - VOLUMES=1 # Portainer
