# --------------------------------------------------------------------------
# Watchtower is awesome. It allows automatically updating Docker containers,
# even itself. It's configured to run once daily at 3AM here.
# --------------------------------------------------------------------------

services:
  # use docker-socket-proxy for watchtower's Docker access
  socket-proxy:
    container_name: watchtower-socket-proxy
    image: tecnativa/docker-socket-proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks: # uses the socket proxy network
      socket_proxy:
        ipv4_address: 172.21.0.253 # manually specify IP address in subnet
    privileged: true
    ports:
      - "127.0.0.1:2375:2375" # NEVER expose this to the internet with port forwarding!
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOG_LEVEL=info
      ## Variables match the URL prefix (i.e. AUTH blocks access to /auth/* parts of the API, etc.).
      ## Granted by Default
      - EVENTS=1
      - PING=1
      - VERSION=1
      ## Revoked by Default
      # Security critical
      - AUTH=0
      - SECRETS=0
      - POST=1
      # Not always needed
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=1
      - INFO=0
      - NETWORKS=1
      - NODES=0
      - PLUGINS=0
      - SERVICES=0
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=0
      - VOLUMES=1

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    environment:
      TZ: America/New_York
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_INCLUDE_STOPPED: true # update stopped containers
      WATCHTOWER_REVIVE_STOPPED: false # but don't start them after
      WATCHTOWER_SCHEDULE: 0 0 3 * * * # daily at 3:00:00 AM
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: ${GMAIL}
      WATCHTOWER_NOTIFICATION_EMAIL_TO: ${GMAIL}
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: smtp.gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 587
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: ${GMAIL}
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: ${GMAIL_PASSWORD} # https://myaccount.google.com/apppasswords
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 30
      WATCHTOWER_NOTIFICATIONS: email
    networks:
      - socket_proxy
      - synobridge
    command: -H tcp://socket-proxy:2375
    restart: unless-stopped

networks:
  socket_proxy:
    external: true
  synobridge:
    external: true
